export GENIN="/Users/benayoun/Softwares/STAR-2.7.7a/genomes/MM10"

######################################### 
# STAR --genomeDir $GENIN --readFilesIn ../FASTQ_HardTrim/J774A1_shIrf2_3utr_rep1_1.fastq.gz   ../FASTQ_HardTrim/J774A1_shIrf2_3utr_rep1_2.fastq.gz   --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix J774A1_shIrf2_3utr_rep1_RNAseq_STAR_  
# STAR --genomeDir $GENIN --readFilesIn ../FASTQ_HardTrim/J774A1_shIrf2_3utr_rep2_1.fastq.gz   ../FASTQ_HardTrim/J774A1_shIrf2_3utr_rep2_2.fastq.gz   --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix J774A1_shIrf2_3utr_rep2_RNAseq_STAR_  
# STAR --genomeDir $GENIN --readFilesIn ../FASTQ_HardTrim/J774A1_shIrf2_3utr_rep3_1.fastq.gz   ../FASTQ_HardTrim/J774A1_shIrf2_3utr_rep3_2.fastq.gz   --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix J774A1_shIrf2_3utr_rep3_RNAseq_STAR_  
# STAR --genomeDir $GENIN --readFilesIn ../FASTQ_HardTrim/J774A1_shIrf2_cds_rep1_1.fastq.gz   ../FASTQ_HardTrim/J774A1_shIrf2_cds_rep1_2.fastq.gz     --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix J774A1_shIrf2_cds_rep1_RNAseq_STAR_  
# STAR --genomeDir $GENIN --readFilesIn ../FASTQ_HardTrim/J774A1_shIrf2_cds_rep2_1.fastq.gz   ../FASTQ_HardTrim/J774A1_shIrf2_cds_rep2_2.fastq.gz     --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix J774A1_shIrf2_cds_rep2_RNAseq_STAR_  
# STAR --genomeDir $GENIN --readFilesIn ../FASTQ_HardTrim/J774A1_shIrf2_cds_rep3_1.fastq.gz   ../FASTQ_HardTrim/J774A1_shIrf2_cds_rep3_2.fastq.gz     --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix J774A1_shIrf2_cds_rep3_RNAseq_STAR_  
# STAR --genomeDir $GENIN --readFilesIn ../FASTQ_HardTrim/J774A1_shLuc_rep1_1.fastq.gz        ../FASTQ_HardTrim/J774A1_shLuc_rep1_2.fastq.gz          --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix J774A1_shLuc_rep1_RNAseq_STAR_  
# STAR --genomeDir $GENIN --readFilesIn ../FASTQ_HardTrim/J774A1_shLuc_rep2_1.fastq.gz        ../FASTQ_HardTrim/J774A1_shLuc_rep2_2.fastq.gz          --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix J774A1_shLuc_rep2_RNAseq_STAR_  
# STAR --genomeDir $GENIN --readFilesIn ../FASTQ_HardTrim/J774A1_shLuc_rep3_1.fastq.gz        ../FASTQ_HardTrim/J774A1_shLuc_rep3_2.fastq.gz          --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix J774A1_shLuc_rep3_RNAseq_STAR_  
# STAR --genomeDir $GENIN --readFilesIn ../FASTQ_HardTrim/J774A1_shNon_rep1_1.fastq.gz        ../FASTQ_HardTrim/J774A1_shNon_rep1_2.fastq.gz          --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix J774A1_shNon_rep1_RNAseq_STAR_  
# STAR --genomeDir $GENIN --readFilesIn ../FASTQ_HardTrim/J774A1_shNon_rep2_1.fastq.gz        ../FASTQ_HardTrim/J774A1_shNon_rep2_2.fastq.gz          --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix J774A1_shNon_rep2_RNAseq_STAR_  
# STAR --genomeDir $GENIN --readFilesIn ../FASTQ_HardTrim/J774A1_shNon_rep3_1.fastq.gz        ../FASTQ_HardTrim/J774A1_shNon_rep3_2.fastq.gz          --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix J774A1_shNon_rep3_RNAseq_STAR_  

########################################## 

featureCounts -t exon -D 1500 -p --primary -T 3 -s 0 -a /Users/benayoun/Softwares/Genomes/mm10_genes.gtf -o 2025-01-23_J774A1_shIRF2_CLEAN_counts_unstranded.txt \
     J774A1_shNon_rep1_RNAseq_STAR_Aligned.sortedByCoord.out.bam       \
     J774A1_shNon_rep2_RNAseq_STAR_Aligned.sortedByCoord.out.bam       \
     J774A1_shNon_rep3_RNAseq_STAR_Aligned.sortedByCoord.out.bam       \
     J774A1_shLuc_rep1_RNAseq_STAR_Aligned.sortedByCoord.out.bam       \
     J774A1_shLuc_rep2_RNAseq_STAR_Aligned.sortedByCoord.out.bam       \
     J774A1_shLuc_rep3_RNAseq_STAR_Aligned.sortedByCoord.out.bam       \
     J774A1_shIrf2_3utr_rep1_RNAseq_STAR_Aligned.sortedByCoord.out.bam \
     J774A1_shIrf2_3utr_rep2_RNAseq_STAR_Aligned.sortedByCoord.out.bam \
     J774A1_shIrf2_3utr_rep3_RNAseq_STAR_Aligned.sortedByCoord.out.bam \
     J774A1_shIrf2_cds_rep1_RNAseq_STAR_Aligned.sortedByCoord.out.bam  \
     J774A1_shIrf2_cds_rep2_RNAseq_STAR_Aligned.sortedByCoord.out.bam  \
     J774A1_shIrf2_cds_rep3_RNAseq_STAR_Aligned.sortedByCoord.out.bam
