export GENIN="/Users/benayoun/Softwares/STAR-2.7.7a/genomes/MM10"

STAR --genomeDir $GENIN --readFilesIn ../FASTQ/GSM2786903_BMDM_Control_rep1_1.fastq.gz     ../FASTQ/GSM2786903_BMDM_Control_rep1_2.fastq.gz        --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2786903_BMDM_Control_rep1_STAR_     
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/GSM2786904_BMDM_Control_rep2_1.fastq.gz     ../FASTQ/GSM2786904_BMDM_Control_rep2_2.fastq.gz        --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2786904_BMDM_Control_rep2_STAR_     
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/GSM2786905_BMDM_Control_rep3_1.fastq.gz     ../FASTQ/GSM2786905_BMDM_Control_rep3_2.fastq.gz        --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2786905_BMDM_Control_rep3_STAR_     
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/GSM2786906_BMDM_IFNgLPS_1h_rep_1_1.fastq.gz ../FASTQ/GSM2786906_BMDM_IFNgLPS_1h_rep_1_2.fastq.gz    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2786906_BMDM_IFNgLPS_1h_rep_1_STAR_ 
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/GSM2786907_BMDM_IFNgLPS_1h_rep_2_1.fastq.gz ../FASTQ/GSM2786907_BMDM_IFNgLPS_1h_rep_2_2.fastq.gz    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2786907_BMDM_IFNgLPS_1h_rep_2_STAR_ 
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/GSM2786908_BMDM_IFNgLPS_1h_rep_3_1.fastq.gz ../FASTQ/GSM2786908_BMDM_IFNgLPS_1h_rep_3_2.fastq.gz    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2786908_BMDM_IFNgLPS_1h_rep_3_STAR_ 
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/GSM2786909_BMDM_IFNgLPS_4h_rep_1_1.fastq.gz ../FASTQ/GSM2786909_BMDM_IFNgLPS_4h_rep_1_2.fastq.gz    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2786909_BMDM_IFNgLPS_4h_rep_1_STAR_ 
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/GSM2786910_BMDM_IFNgLPS_4h_rep_2_1.fastq.gz ../FASTQ/GSM2786910_BMDM_IFNgLPS_4h_rep_2_2.fastq.gz    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2786910_BMDM_IFNgLPS_4h_rep_2_STAR_ 
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/GSM2786911_BMDM_IFNgLPS_4h_rep_3_1.fastq.gz ../FASTQ/GSM2786911_BMDM_IFNgLPS_4h_rep_3_2.fastq.gz    --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2786911_BMDM_IFNgLPS_4h_rep_3_STAR_ 
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/GSM2786912_BMDM_IFNgLPS_12h_rep_1_1.fastq.gz ../FASTQ/GSM2786912_BMDM_IFNgLPS_12h_rep_1_2.fastq.gz  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2786912_BMDM_IFNgLPS_12h_rep_1_STAR_
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/GSM2786913_BMDM_IFNgLPS_12h_rep_2_1.fastq.gz ../FASTQ/GSM2786913_BMDM_IFNgLPS_12h_rep_2_2.fastq.gz  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2786913_BMDM_IFNgLPS_12h_rep_2_STAR_
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/GSM2786914_BMDM_IFNgLPS_12h_rep_3_1.fastq.gz ../FASTQ/GSM2786914_BMDM_IFNgLPS_12h_rep_3_2.fastq.gz  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2786914_BMDM_IFNgLPS_12h_rep_3_STAR_
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/GSM2786915_BMDM_IFNgLPS_24h_rep_1_1.fastq.gz ../FASTQ/GSM2786915_BMDM_IFNgLPS_24h_rep_1_2.fastq.gz  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2786915_BMDM_IFNgLPS_24h_rep_1_STAR_
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/GSM2786916_BMDM_IFNgLPS_24h_rep_2_1.fastq.gz ../FASTQ/GSM2786916_BMDM_IFNgLPS_24h_rep_2_2.fastq.gz  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2786916_BMDM_IFNgLPS_24h_rep_2_STAR_
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/GSM2786917_BMDM_IFNgLPS_24h_rep_3_1.fastq.gz ../FASTQ/GSM2786917_BMDM_IFNgLPS_24h_rep_3_2.fastq.gz  --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2786917_BMDM_IFNgLPS_24h_rep_3_STAR_
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/GSM2786918_BMDM_IL4_12h_rep_1_1.fastq.gz     ../FASTQ/GSM2786918_BMDM_IL4_12h_rep_1_2.fastq.gz      --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2786918_BMDM_IL4_12h_rep_1_STAR_    
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/GSM2786919_BMDM_IL4_12h_rep_2_1.fastq.gz     ../FASTQ/GSM2786919_BMDM_IL4_12h_rep_2_2.fastq.gz      --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2786919_BMDM_IL4_12h_rep_2_STAR_    
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/GSM2786920_BMDM_IL4_12h_rep_3_1.fastq.gz     ../FASTQ/GSM2786920_BMDM_IL4_12h_rep_3_2.fastq.gz      --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2786920_BMDM_IL4_12h_rep_3_STAR_    
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/GSM2786921_BMDM_IL13_12h_rep_1_1.fastq.gz    ../FASTQ/GSM2786921_BMDM_IL13_12h_rep_1_2.fastq.gz     --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2786921_BMDM_IL13_12h_rep_1_STAR_   
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/GSM2786922_BMDM_IL13_12h_rep_2_1.fastq.gz    ../FASTQ/GSM2786922_BMDM_IL13_12h_rep_2_2.fastq.gz     --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2786922_BMDM_IL13_12h_rep_2_STAR_   
STAR --genomeDir $GENIN --readFilesIn ../FASTQ/GSM2786923_BMDM_IL13_12h_rep_3_1.fastq.gz    ../FASTQ/GSM2786923_BMDM_IL13_12h_rep_3_2.fastq.gz     --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate --outFileNamePrefix GSM2786923_BMDM_IL13_12h_rep_3_STAR_   
