export GENIN="/mnt/data/Data/FASTQ/J775_E2/STAR/MM10"

# 2025-11-25
# map using the same STAR version as the other datasets
# on jarvis

FQDIR='/mnt/data/Data/FASTQ/LTE2/FASTQ'

## LTE2 cohort 6
~/Softwares/STAR-2.7.7a/bin/Linux_x86_64/STAR --genomeDir $GENIN --readFilesIn $FQDIR/PeriMac_LTE2_01_O_E2_1.fastq.gz    $FQDIR/PeriMac_LTE2_01_O_E2_2.fastq.gz   --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand zcat --runThreadN 10 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix PeriMac_LTE2_01_O_E2_RNAseq_STAR_
~/Softwares/STAR-2.7.7a/bin/Linux_x86_64/STAR --genomeDir $GENIN --readFilesIn $FQDIR/PeriMac_LTE2_03_Y_Ve_1.fastq.gz    $FQDIR/PeriMac_LTE2_03_Y_Ve_2.fastq.gz   --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand zcat --runThreadN 10 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix PeriMac_LTE2_03_Y_Ve_RNAseq_STAR_
~/Softwares/STAR-2.7.7a/bin/Linux_x86_64/STAR --genomeDir $GENIN --readFilesIn $FQDIR/PeriMac_LTE2_05_O_Ve_1.fastq.gz    $FQDIR/PeriMac_LTE2_05_O_Ve_2.fastq.gz   --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand zcat --runThreadN 10 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix PeriMac_LTE2_05_O_Ve_RNAseq_STAR_
~/Softwares/STAR-2.7.7a/bin/Linux_x86_64/STAR --genomeDir $GENIN --readFilesIn $FQDIR/PeriMac_LTE2_06_Y_Ve_1.fastq.gz    $FQDIR/PeriMac_LTE2_06_Y_Ve_2.fastq.gz   --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand zcat --runThreadN 10 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix PeriMac_LTE2_06_Y_Ve_RNAseq_STAR_
~/Softwares/STAR-2.7.7a/bin/Linux_x86_64/STAR --genomeDir $GENIN --readFilesIn $FQDIR/PeriMac_LTE2_07_O_E2_1.fastq.gz    $FQDIR/PeriMac_LTE2_07_O_E2_2.fastq.gz   --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand zcat --runThreadN 10 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix PeriMac_LTE2_07_O_E2_RNAseq_STAR_
~/Softwares/STAR-2.7.7a/bin/Linux_x86_64/STAR --genomeDir $GENIN --readFilesIn $FQDIR/PeriMac_LTE2_08_O_Ve_1.fastq.gz    $FQDIR/PeriMac_LTE2_08_O_Ve_2.fastq.gz   --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand zcat --runThreadN 10 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix PeriMac_LTE2_08_O_Ve_RNAseq_STAR_
~/Softwares/STAR-2.7.7a/bin/Linux_x86_64/STAR --genomeDir $GENIN --readFilesIn $FQDIR/PeriMac_LTE2_09_Y_Ve_1.fastq.gz    $FQDIR/PeriMac_LTE2_09_Y_Ve_2.fastq.gz   --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand zcat --runThreadN 10 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix PeriMac_LTE2_09_Y_Ve_RNAseq_STAR_
~/Softwares/STAR-2.7.7a/bin/Linux_x86_64/STAR --genomeDir $GENIN --readFilesIn $FQDIR/PeriMac_LTE2_10_O_E2_1.fastq.gz    $FQDIR/PeriMac_LTE2_10_O_E2_2.fastq.gz   --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand zcat --runThreadN 10 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix PeriMac_LTE2_10_O_E2_RNAseq_STAR_
~/Softwares/STAR-2.7.7a/bin/Linux_x86_64/STAR --genomeDir $GENIN --readFilesIn $FQDIR/PeriMac_LTE2_11_O_Ve_1.fastq.gz    $FQDIR/PeriMac_LTE2_11_O_Ve_2.fastq.gz   --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand zcat --runThreadN 10 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix PeriMac_LTE2_11_O_Ve_RNAseq_STAR_
~/Softwares/STAR-2.7.7a/bin/Linux_x86_64/STAR --genomeDir $GENIN --readFilesIn $FQDIR/PeriMac_LTE2_12_Y_Ve_1.fastq.gz    $FQDIR/PeriMac_LTE2_12_Y_Ve_2.fastq.gz   --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand zcat --runThreadN 10 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix PeriMac_LTE2_12_Y_Ve_RNAseq_STAR_
~/Softwares/STAR-2.7.7a/bin/Linux_x86_64/STAR --genomeDir $GENIN --readFilesIn $FQDIR/PeriMac_LTE2_13_O_E2_1.fastq.gz    $FQDIR/PeriMac_LTE2_13_O_E2_2.fastq.gz   --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand zcat --runThreadN 10 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix PeriMac_LTE2_13_O_E2_RNAseq_STAR_
~/Softwares/STAR-2.7.7a/bin/Linux_x86_64/STAR --genomeDir $GENIN --readFilesIn $FQDIR/PeriMac_LTE2_14_O_Ve_1.fastq.gz    $FQDIR/PeriMac_LTE2_14_O_Ve_2.fastq.gz   --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand zcat --runThreadN 10 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix PeriMac_LTE2_14_O_Ve_RNAseq_STAR_
~/Softwares/STAR-2.7.7a/bin/Linux_x86_64/STAR --genomeDir $GENIN --readFilesIn $FQDIR/PeriMac_LTE2_15_Y_Ve_1.fastq.gz    $FQDIR/PeriMac_LTE2_15_Y_Ve_2.fastq.gz   --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand zcat --runThreadN 10 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix PeriMac_LTE2_15_Y_Ve_RNAseq_STAR_