export GENIN="/Users/benayoun/Softwares/STAR-2.7.7a/genomes/MM10"

# 2022-03-01
# remap with additional depth AND allowing some overlap between Forward and Reverse reads
# Relax parameters on mapped length as well [https://github.com/alexdobin/STAR/issues/169]

## NIA cohort
#STAR --genomeDir $GENIN --readFilesIn ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_OF1_RNAseq_2lanes_1.fastq.gz ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_OF1_RNAseq_2lanes_2.fastq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix PeriMac_NIA_AC41_OF1_RNAseq_2lanes_STAR_
#STAR --genomeDir $GENIN --readFilesIn ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_OF2_RNAseq_2lanes_1.fastq.gz ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_OF2_RNAseq_2lanes_2.fastq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix PeriMac_NIA_AC41_OF2_RNAseq_2lanes_STAR_
#STAR --genomeDir $GENIN --readFilesIn ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_OF3_RNAseq_2lanes_1.fastq.gz ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_OF3_RNAseq_2lanes_2.fastq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix PeriMac_NIA_AC41_OF3_RNAseq_2lanes_STAR_
#STAR --genomeDir $GENIN --readFilesIn ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_OF4_RNAseq_2lanes_1.fastq.gz ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_OF4_RNAseq_2lanes_2.fastq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix PeriMac_NIA_AC41_OF4_RNAseq_2lanes_STAR_
#STAR --genomeDir $GENIN --readFilesIn ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_OF5_RNAseq_2lanes_1.fastq.gz ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_OF5_RNAseq_2lanes_2.fastq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix PeriMac_NIA_AC41_OF5_RNAseq_2lanes_STAR_
#STAR --genomeDir $GENIN --readFilesIn ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_OM1_RNAseq_2lanes_1.fastq.gz ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_OM1_RNAseq_2lanes_2.fastq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix PeriMac_NIA_AC41_OM1_RNAseq_2lanes_STAR_
#STAR --genomeDir $GENIN --readFilesIn ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_OM2_RNAseq_2lanes_1.fastq.gz ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_OM2_RNAseq_2lanes_2.fastq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix PeriMac_NIA_AC41_OM2_RNAseq_2lanes_STAR_
#STAR --genomeDir $GENIN --readFilesIn ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_OM3_RNAseq_2lanes_1.fastq.gz ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_OM3_RNAseq_2lanes_2.fastq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix PeriMac_NIA_AC41_OM3_RNAseq_2lanes_STAR_
#STAR --genomeDir $GENIN --readFilesIn ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_OM4_RNAseq_2lanes_1.fastq.gz ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_OM4_RNAseq_2lanes_2.fastq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix PeriMac_NIA_AC41_OM4_RNAseq_2lanes_STAR_
#STAR --genomeDir $GENIN --readFilesIn ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_OM5_RNAseq_2lanes_1.fastq.gz ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_OM5_RNAseq_2lanes_2.fastq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix PeriMac_NIA_AC41_OM5_RNAseq_2lanes_STAR_
#STAR --genomeDir $GENIN --readFilesIn ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_YF1_RNAseq_2lanes_1.fastq.gz ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_YF1_RNAseq_2lanes_2.fastq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix PeriMac_NIA_AC41_YF1_RNAseq_2lanes_STAR_
#STAR --genomeDir $GENIN --readFilesIn ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_YF2_RNAseq_2lanes_1.fastq.gz ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_YF2_RNAseq_2lanes_2.fastq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix PeriMac_NIA_AC41_YF2_RNAseq_2lanes_STAR_
#STAR --genomeDir $GENIN --readFilesIn ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_YF3_RNAseq_2lanes_1.fastq.gz ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_YF3_RNAseq_2lanes_2.fastq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix PeriMac_NIA_AC41_YF3_RNAseq_2lanes_STAR_
#STAR --genomeDir $GENIN --readFilesIn ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_YF4_RNAseq_2lanes_1.fastq.gz ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_YF4_RNAseq_2lanes_2.fastq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix PeriMac_NIA_AC41_YF4_RNAseq_2lanes_STAR_
#STAR --genomeDir $GENIN --readFilesIn ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_YF5_RNAseq_2lanes_1.fastq.gz ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_YF5_RNAseq_2lanes_2.fastq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix PeriMac_NIA_AC41_YF5_RNAseq_2lanes_STAR_
#STAR --genomeDir $GENIN --readFilesIn ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_YM1_RNAseq_2lanes_1.fastq.gz ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_YM1_RNAseq_2lanes_2.fastq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix PeriMac_NIA_AC41_YM1_RNAseq_2lanes_STAR_
#STAR --genomeDir $GENIN --readFilesIn ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_YM2_RNAseq_2lanes_1.fastq.gz ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_YM2_RNAseq_2lanes_2.fastq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix PeriMac_NIA_AC41_YM2_RNAseq_2lanes_STAR_
#STAR --genomeDir $GENIN --readFilesIn ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_YM3_RNAseq_2lanes_1.fastq.gz ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_YM3_RNAseq_2lanes_2.fastq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix PeriMac_NIA_AC41_YM3_RNAseq_2lanes_STAR_
#STAR --genomeDir $GENIN --readFilesIn ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_YM4_RNAseq_2lanes_1.fastq.gz ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_YM4_RNAseq_2lanes_2.fastq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix PeriMac_NIA_AC41_YM4_RNAseq_2lanes_STAR_
#STAR --genomeDir $GENIN --readFilesIn ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_YM5_RNAseq_2lanes_1.fastq.gz ../FASTQ_HardTrim/PeriMac_AC41/2Lanes/PeriMac_AC41_YM5_RNAseq_2lanes_2.fastq.gz  --outFilterScoreMinOverLread 0.4 --outFilterMatchNminOverLread 0.4 --readFilesCommand gzcat --runThreadN 1 --outFilterMultimapNmax 50 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --outSAMtype BAM SortedByCoordinate  --alignEndsProtrude 15 ConcordantPair --outFileNamePrefix PeriMac_NIA_AC41_YM5_RNAseq_2lanes_STAR_


sh count_reads_v3.sh


